src/Entity/Store/Brand.php
<?php

namespace App\Entity\Store;

use App\Repository\Store\BrandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BrandRepository::class)]
class Brand
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'brand', targetEntity: Product::class)]
    private Collection $products;

    public function __construct()
    {
       $this->products = new ArrayCollection();
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setBrand($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            ($this->products->removeElement($product));
            // set the owning side to null (unless already changed)
            if ($product->getBrand() === $this) {
                $product->setBrand(null);
            }
        }

        return $this;
    }

    /**
     * @param Collection<int, Product> $products
     */
    public function setProducts(Collection $products): void
    {
        $this->products = $products;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Entity/Store/Color.php
<?php

namespace App\Entity\Store;

use App\Repository\Store\ColorRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ColorRepository::class)]
class Color
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Entity/Store/Comment.php
<?php

namespace App\Entity\Store;

use App\Repository\Store\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
#[ORM\Table('sto_comment')]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255)]
    private ?string $message = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?Product $product = null;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }
}

src/Entity/Store/Image.php
<?php

namespace App\Entity\Store;

use App\Repository\ImageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImageRepository::class)]
#[ORM\Table(name: 'sto_image')]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $url;

    #[ORM\Column(length: 255)]
    private ?string $alt;

    public function __construct(
        string $url,
        string $alt
    ){
        $this->url = $url;
        $this->alt = $alt;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }
}

src/Entity/Store/Product.php
<?php

namespace App\Entity\Store;

use App\Entity\Store\Comment;
use App\Repository\Store\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\String\Slugger\AsciiSlugger;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at;

    #[ORM\OneToOne(targetEntity: Image::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(name: 'sto_image_id', nullable: false)]
    private ?Image $image = null;

    #[ORM\Column(length: 1500)]
    private ?string $long_description = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\ManyToOne(targetEntity: Brand::class, inversedBy: 'products')]
    #[ORM\JoinColumn(name: 'sto_brand_id')]
    private ?Brand $brand = null;

    #[ORM\ManyToMany(targetEntity: Color::class)]
    #[ORM\JoinTable(name: 'sto_product_color')]
    private Collection $colors;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Comment::class, cascade: ['persist', 'remove'])]
    private Collection $comments;

    public function __construct(
        Image $image,
        string $name,
        string $description,
        float $price
    )
    {
        $this->image = $image;
        $this->name = $name;
        $this->description = $description;
        $this->price = $price;

        $slugger = new AsciiSlugger();
        $this->slug = $slugger->slug($name)->toString();

        $this->created_at = new \DateTimeImmutable();
        $this->colors = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @return Collection
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment) && $comment->getProduct() === $this) {
            $this->comments->add($comment);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        $this->comments->removeElement($comment);

        return $this;
    }




    /**
     * @return Collection
     */
    public function getColors(): Collection
    {
        return $this->colors;
    }

    public function addColor(Color $color): self
    {
        if (!$this->colors->contains($color)) {
            $this->colors[] = $color;
        }

        return $this;
    }

    public function removeColor(Color $color): self
    {
        if ($this->colors->contains($color)) {
            $this->colors->removeElement($color);
        }

        return $this;
    }

    /**
     * @return Brand|null
     */
    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    /**
     * @param Brand|null $brand
     */
    public function setBrand(?Brand $brand): void
    {
        $this->brand = $brand;
    }

    /**
     * @return Image|null
     */
    public function getImage(): ?Image
    {
        return $this->image;
    }

    /**
     * @param Image|null $image
     */
    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getLongDescription(): ?string
    {
        return $this->long_description;
    }

    public function setLongDescription(string $long_description): self
    {
        $this->long_description = $long_description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Controller/StoreController.php
<?php

namespace App\Controller;

use App\Entity\Store\Comment;
use App\Form\CommentType;
use App\Manager\Store\ProductManager;
use App\Repository\Store\BrandRepository;
use App\Repository\Store\CommentRepository;
use App\Repository\Store\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class StoreController extends AbstractController
{

    public function  __construct(
        private ProductRepository $productRepository,
        private BrandRepository $brandRepository,
        private CommentRepository $commentRepository,
        private ProductManager $productManager,
    ){
    }

    #[Route('/store', name: 'app_store')]
    public function index(): Response
    {
        $products = $this->productRepository->findAll();

        $brands = $this->brandRepository->findAll();

        return $this->render('store/product-list.html.twig', [
            'products' => $products,
            'brands' => $brands,
            'brand' => null,
        ]);
    }

    #[Route('/store/{id}', name: 'app_store_brand', requirements: ['id' => '\d+'])]
    public function indexBrand(int $id): Response
    {
        $brand = $this->brandRepository->findOneBy(['id' => $id]);
        $products = $this->productRepository->findByBrand($brand);


        $brands = $this->brandRepository->findAll();

        return $this->render('store/product-list.html.twig', [
            'products' => $products,
            'brands' => $brands,
            'activeBrand' => $brand,
        ]);
    }

    #[Route('/store/product/{id}/details/{slug}', name: 'store_show_product', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    public function showProduct(int $id, string $slug, Request $request): Response
    {
        $product = $this->productRepository->findOneById($id);
        $brands = $this->brandRepository->findAll();

        if($product === null){
            throw new NotFoundHttpException();
        }

        if($product->getSlug() !== $slug){
            return $this->redirectToRoute('store_show_product', [
                'id' => $product->getId(),
                'slug' => $product->getSlug(),
            ], Response::HTTP_MOVED_PERMANENTLY);
        }

        //form
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->productManager->addComment($comment, $product);

            return $this->redirectToRoute('store_show_product', [
                'id' => $product->getId(),
                'slug' => $product->getSlug(),
            ]);
        }


        return $this->render('store/product-detail.html.twig', [
            'form' => $form->createView(),
            'product' => $product,
            'id' => $id,
            'slug' => $slug,
            'brands' => $brands,
        ]);
    }
}

templates/store/product-detail.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
    <div class="row">
        {{ block("brands", "blocks/brands.html.twig") }}

        <div class="col-md-9">
            {% for flash_type, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ flash_type }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endfor %}
            <p class="lead">
                {{ product.name }}
                <a href="#" class="btn btn-default pull-right">Retour aux produits</a>
            </p>
            <div class="row">
                <div class="thumbnail">
                    <img class="img-responsive" src="img/products/shoe-1.jpg" alt="">
                    <div class="caption-full">
                        <h4 class="pull-right"><span class="badge">120,00 €</span></h4>
                        <img src="{{ asset(product.image.url) }}">
                        <h3>{{ product.name }}</h3>
                        <p>{{ product.description }}</p>
                        <p>
                            {{ product.longDescription }}
                        </p>
                        {% for color in product.colors %}
                            <span class="label label-default">{{ color.name }}</span>
                        {% endfor %}
                    </div>
                </div>

                <div class="well">
                    <p class="pull-right label label-success">Actuellement {{ product.comments | length }} avis</p>
                    {% for comment in product.comments %}
                        <div class="row">
                            <div class="col-md-12">
                                <span class="label label-info">{{ comment.pseudo }}</span>
                                <span class="label label-default pull-right">{{ comment.createdAt.format('d/m/Y') }}</span>
                                <p>{{ comment.message }}</p>
                            </div>
                        </div>
                        <hr/>
                    {% endfor %}



                    <div>
                        {{ form_start(form) }}
                            <div class="form-group">
                                {{ form_label(form.pseudo) }}
                                {{ form_errors(form.pseudo) }}
                                {{ form_widget(form.pseudo, {'attr': {'class': 'form-control', 'placeholder': form.pseudo.vars.label }}) }}
                            </div>

                            <div class="form-group">
                                {{ form_label(form.message) }}
                                {{ form_errors(form.message) }}
                                {{ form_widget(form.message, {'attr': {'class': 'form-control', 'placeholder': form.message.vars.label }}) }}
                            </div>

                            <button type="submit" class="btn btn-info">Envoyer mon message</button>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr/>

{% endblock %}

templates/store/product-list.html.twig
{% extends 'layout.html.twig' %}

{% block tittle %}Produits | {{ parent() }}{% endblock %}

{% block content %}
	<div class="row">
		{{ block("brands", "blocks/brands.html.twig") }}

		<div class="col-md-9">
			<p class="lead">Nos produits {{ activeBrand is defined ? activeBrand.name : "\"Toute les marques\"" }}</p>
			<div class="row text-center">
				{% if products|length != 0 %}
					{% for key,product in products %}
						{{ block("productList", "blocks/product.html.twig") }}
					{% endfor %}
				{% else %}
					<p>Aucun produit</p>
				{% endif %}
			</div>

			<div class="row text-center">
				<nav>
					<ul class="pagination pagination-lg">
						<li>
							<a href="#" aria-label="Précédent">
								<span aria-hidden="true">&laquo;</span>
							</a>
						</li>
						<li class="active">
							<a href="#">1</a>
						</li>
						<li>
							<a href="#">2</a>
						</li>
						<li>
							<a href="#">3</a>
						</li>
						<li>
							<a href="#">4</a>
						</li>
						<li>
							<a href="#">5</a>
						</li>
						<li>
							<a href="#" aria-label="Suivant">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</div>

	<hr/>
{% endblock %}